# autogenerated
variable "project_name" {
  description = "Name of the project"
  type        = string
}

variable "component_name" {
  description = "Name of the component"
  type        = string
  default     = "test"
}

variable "environment" {
  description = "Environment name"
  type        = string
}
